{% set data = load_setuptools()%}
package:
  name: lspcreport
  version: "0.0.1"

source:
  path: ../../

build:
  script: python setup.py install
  number: 3

requirements:
  build:
    - python
    - setuptools
    - pandas
    - pytest
    - swmmreport
  run:
    - python
    - setuptools
    - pandas
    - swmmreport

test:
  requires:
    - pytest
    - swmmreport
  imports:
    - lspcreport
  commands:
    - python -c "print('hello world')"
    - python -c "import sys, lspcreport; sys.exit(lspcreport.test())"

about:
  home: https://github.com/lucashtnguyen/lspcreport.git
  license:  BSD License
  summary: 'Basic water quality inflow/outflow analysis tools'

